name: pruebas hola mundo docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1 - Checkout del repositorio
        uses: actions/checkout@v4

      - name: Paso 2 - Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Paso 3 - Construir imagen Docker
        run: docker build -t contenedor .

      - name: Paso 4 - Ejecutar extract.py
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/src/edu_pad/static/csv":/pad_2025_1_2/static/csv \
            -v "${{ github.workspace }}/src/edu_pad/static/db":/pad_2025_1_2/static/db \
            contenedor python3 src/edu_pad/extract.py

      - name: Paso 5 - Ejecutar clean.py
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/src/edu_pad/static/csv":/pad_2025_1_2/static/csv \
            -v "${{ github.workspace }}/src/edu_pad/static/db":/pad_2025_1_2/static/db \
            contenedor python3 src/edu_pad/clean.py

      - name: Paso 6 - Ejecutar ingest.py
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/src/edu_pad/static/csv":/pad_2025_1_2/static/csv \
            -v "${{ github.workspace }}/src/edu_pad/static/db":/pad_2025_1_2/static/db \
            contenedor python3 src/edu_pad/ingest.py